/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./App.{js,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],

	presets: [require("nativewind/preset")],
	theme: {
		extend: {
			colors: {
				background: "#F3F5F9",
				backgroundDark: "#121A2A",
				surface: "#FFFFFF",
				surfaceDark: "#1A2436",
				surfaceElevated: "#F8FAFC",
				surfaceElevatedDark: "#202B40",
				surfaceSoft: "#E9EEF6",
				surfaceSoftDark: "#26334A",
				text: "#1D293D",
				textDark: "#EEF4FF",
				textMuted: "#64748B",
				textMutedDark: "#B6C2D5",
				textInverse: "#FFFFFF",
				textInverseDark: "#0F172A",
				border: "#CBD5E1",
				borderDark: "#3A4961",
				borderStrong: "#94A3B8",
				borderStrongDark: "#596A84",
				primary: "#5B79C7",
				primaryDark: "#86A2E8",
				primaryPressed: "#4869B8",
				primaryPressedDark: "#6F8DDA",
				primarySoft: "#E5ECFA",
				primarySoftDark: "#273B63",
				primarySoftText: "#243D79",
				primarySoftTextDark: "#DCE7FF",
				secondary: "#A7A8A9",
				secondaryDark: "#8C96A8",
				secondarySoft: "#E2E8F0",
				secondarySoftDark: "#2A3548",
				success: "#16A34A",
				successDark: "#4ADE80",
				successSoft: "#DCFCE7",
				successSoftDark: "#12351F",
				warning: "#D97706",
				warningDark: "#FBBF24",
				warningSoft: "#FEF3C7",
				warningSoftDark: "#3A2A0A",
				danger: "#DC2626",
				dangerDark: "#F87171",
				dangerSoft: "#FEE2E2",
				dangerSoftDark: "#3B1618",
				info: "#2563EB",
				infoDark: "#60A5FA",
				infoSoft: "#DBEAFE",
				infoSoftDark: "#142B4D",
				disabledBg: "#E5E7EB",
				disabledBgDark: "#263041",
				disabledText: "#9CA3AF",
				disabledTextDark: "#78869A",
				teColorPrincipal: "#5B79C7",
				teColorPrincipalOscuro: "#202B40",
				teColorPrincipalMedio: "#8EA7E5",
				teColorPrincipalClaro: "#E5ECFA",
				teColorSecundario: "#A7A8A9",
				teColorSecundarioMedio: "#E2E8F0",
				teColorSecundarioClaro: "#F8FAFC",
				teColorTurnoAbierto: "#16A34A",
				teColorTurnoPendiente: "#D97706",
				teColorTurnoCierreEspecial: "#DC2626",
				teColorTurnoCerrado: "#2563EB",
				teColorTurnoAbrir: "#E5ECFA",
			},
		},
	},
	plugins: [],
};
