export type TraspasoDTO = {
  id_trapaso?: string | null; // ID proveniente de MongoDB (Ojo: sin la 's')
  clave?: string;
  bod_origen: number;
  bod_destino: number;
  id_tanque_destino: number;
  regla_altura_inicial: string;
  regla_altura_final: string;
  litros_tanque_inicial: number;
  litros_tanque_final: number;
  temp_inicial: number;
  temp_final: number;
  id_pico: number;
  taxilitro_inicial: number;
  taxilitro_final: number;
  litros_pico: number;
  obs_traspaso: string;
  fecha: string;
  hora: string;
  id_playero: number;
  id_encargado_receptor: number;
  foto_medicion_inicial?: string[];
  foto_medicion_final?: string[];
  firma_receptor?: string[];
  foto_obs_traspaso?: string[];
  foto_taxilitro?: string[];
  foto_taxilitro_fin?: string[];
  last_id_salida?: number | null;
  obs_adicional?: string | null;
  appte?: string | null;
  id_autorizado?: number | null;
  corte_id?: number | null;
};